from pathlib import Path

MODEL_PATH = Path("models/hand_landmarker.task")
RAW_DATA_PATH = Path("data/raw/gestures.json")
INSPECTION_PLOTS_PATH = Path("data/inspection")

PINCH_START_RATIO = 0.35
PINCH_END_RATIO = 0.50

PINCH_START_CONFIRM_FRAMES = 2
PINCH_END_CONFIRM_FRAMES = 2

MIN_GESTURE_POINTS = 10
MIN_GESTURE_DURATION_MS = 200

MAX_LOST_FRAMES = 5

SMOOTHING_ALPHA = 0.80

NUM_HANDS = 2

CASTING_HAND = "Left"
TARGET_SAMPLES_PER_SPELL = 5
